version: "3"
services:
  application:
    image: resume-tracker:latest
    depends_on:
      db_primary:
        condition: service_started
    ports:
      - '0.0.0.0:8080:80'
    networks:
      default:
        aliases:
          - application_cluster
  # I THINK APPLICATION IS DONE BUT NOT SURE
  
  db_primary:
    build: db-primary
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    depends_on:
      db_replica:
        condition: service_started
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tracker_db
      - PG_APP_USER=appUser
      - PG_APP_PW=appPW
      - PG_REP_USER=repl
      - PG_REP_PASSWORD=repl
    networks:
      default:
        aliases:
          - application_cluster
  db_replica:
    build: db-replica
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tracker_db
      - PG_REP_USER=repl
      - PG_REP_PASSWORD=repl
      - PG_MASTER_HOST=pg_master
    networks:
      default:
        aliases:
          - application_cluster

